### ISSUE TITLE
Aplicar filtro no DataTable quando carregar a página

### ISSUE THREAD

**Issue by danielnsilva** [CBSIUFAC/SisProBom-AC#1]
Quando os dados do DataTable são mostrados pela primeira vez os filtros ainda não foram aplicados. Por exemplo, na listagem de documentos, é interessante mostrar inicialmente os documentos não arquivados, mas ao carregar o DataTable todos os documentos são mostrados, sendo que o valor padrão do filtro da coluna "Arquivado" (que é "Não") só é aplicado quando o valor de algum filtro é modificado.

**Comment by rosilva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Teste](https://trello.com/c/yVIUrJoe/1-teste)
